### ISSUE TITLE
Is jest-csl currently running

### ISSUE THREAD

**Issue by denismaier** [cormacrelf/jest-csl#3]
I've had to reinstall my computer, and now I cannot run tests that used to work on my last installation... Running `yarn test` throws those errors:

```
Determining test suites to run...Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)


  ● Test suite failed to run

    Error: spawn git ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
        at onErrorNT (internal/child_process.js:415:16)
        at process._tickCallback (internal/process/next_tick.js:63:19)

      at node_modules/simple-git/promise.js:62:29
      at Git.handler (node_modules/simple-git/src/git.js:1325:18)
      at Function.Git.fail (node_modules/simple-git/src/git.js:1484:18)
      at fail (node_modules/simple-git/src/git.js:1442:20)
      at Object.onError (node_modules/simple-git/src/git.js:1321:10)
      at node_modules/simple-git/src/git.js:1448:24

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Done in 21.91s.
```

Any ideas what I am doing wrong?

**Comment by denismaier** [comment]
Oh. I had to install git first. Now it works. Sorry for the noise.
